### ISSUE TITLE
很不错的鹅厂工具

### ISSUE THREAD

**Issue by yingkong1987** [yulingtianxia/TFSHelper#1]
1.我复制tfs链接的时候finder没有自动打开跳转链接.不过剪切板中的字符串已经被替换好了.
2.软件没有快捷的关闭按钮.

**Comment by yulingtianxia** [comment]
1. 可能是你的链接格式不对，或者不是纯粹的tfs链接，比如其中掺杂了其他文字。
2. 关闭按钮和开机自启动功能后续都会加入

**Comment by yulingtianxia** [comment]
已解决

**Comment by yingkong1987** [comment]
但是用剪切板中已经替换好的链接直接丢进去跳转是OK的.

PS.想请问下问题原因

**Comment by yulingtianxia** [comment]
因为你描述的问题在我这没有重现过，所以我也没发现原因，你可以下载最新的release试试是否还有类似问题：）
