### ISSUE TITLE
链接不成功的时候会不断重试

### ISSUE THREAD

**Issue by yingkong1987** [yulingtianxia/TFSHelper#2]
![779f07a0-0a83-4325-9321-52e9e3fb1d5e](https://cloud.githubusercontent.com/assets/2038099/11467578/07530d40-9784-11e5-9713-71487975a23e.png)

search domain已设置. 然后点确定后又开始重试.

**Comment by yulingtianxia** [comment]
是手动点击“打开链接”按钮后么？还是复制了某个链接后呢？麻烦能发下你的系统版本和想要连接的 tfs 连接么？

**Comment by yingkong1987** [comment]
是自动复制了某个链接后就这样的. 版本是最新的release版本. 地址是 \tencent.com\tfs\软件\常用软件.
他是大概每隔5s就增加一个正在链接.

**Comment by yulingtianxia** [comment]
请问这个 bug 是必现的么？“自动复制”的意思是复制后自动打开链接对吧？我的系统是10.11的，并没有发生过此类问题。能麻烦提供下系统版本么？

**Comment by yingkong1987** [comment]
系统版本:10.11.1 (15B42). 当天是必现的,后来没试过了.

**Comment by yulingtianxia** [comment]
当其他应用向粘贴板写入信息时也可能触发自动连接 tfs，已调整粘贴板策略，

**Comment by yingkong1987** [comment]
手动点赞!
