### ISSUE TITLE
Internation version

### ISSUE THREAD

**Issue by andreykhr** [yulingtianxia/TFSHelper#5]
Will you plan translate this app to another languages?
- English?
- Russian?

You can export string constants to JSON file, and someone else can translate. I can translate to Russian from English.

**Comment by yulingtianxia** [comment]
@andreykhr

**Comment by yulingtianxia** [comment]
Thanks for your attention. @andreykhr 
This app is developed for Tencent staff (Yeah, almost Chinese), the "T" in "TFS" means Tencent.
Emmm... there is no translation plan so far.

**Comment by andreykhr** [comment]
Ouch!.. I think it was Team Foundation Server
Ok thanks
